### ISSUE TITLE
Postgres unknown host exception in Airflow quickstart 

### ISSUE THREAD

**Issue by merobi-hub** [OpenLineage/docs#282]
Barring an issue with my local environment, there seems to be a bug in the quickstart in the API container configuration.

```
2024-02-13 11:25:01 ERROR [2024-02-13 16:25:01,522] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
2024-02-13 11:25:01 ! java.net.UnknownHostException: postgres
2024-02-13 11:25:01 ! at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572)
2024-02-13 11:25:01 ! at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
2024-02-13 11:25:01 ! at java.base/java.net.Socket.connect(Socket.java:633)
2024-02-13 11:25:01 ! at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
2024-02-13 11:25:01 ! at org.postgresql.core.PGStream.<init>(PGStream.java:98)
2024-02-13 11:25:01 ! at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
2024-02-13 11:25:01 ! at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
2024-02-13 11:25:01 ! ... 26 common frames omitted
2024-02-13 11:25:01 ! Causing: org.postgresql.util.PSQLException: The connection attempt failed.
2024-02-13 11:25:01 ! at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
2024-02-13 11:25:01 ! at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
2024-02-13 11:25:01 ! at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
2024-02-13 11:25:01 ! at org.postgresql.Driver.makeConnection(Driver.java:443)
2024-02-13 11:25:01 ! at org.postgresql.Driver.connect(Driver.java:297)
2024-02-13 11:25:01 ! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:346)
2024-02-13 11:25:01 ! at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:227)
2024-02-13 11:25:01 ! at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:772)
2024-02-13 11:25:01 ! at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:700)
2024-02-13 11:25:01 ! at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:499)
2024-02-13 11:25:01 ! at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:155)
2024-02-13 11:25:01 ! at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
2024-02-13 11:25:01 ! at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
2024-02-13 11:25:01 ! at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131)
2024-02-13 11:25:01 ! at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
2024-02-13 11:25:01 ! at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
2024-02-13 11:25:01 ! at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:147)
2024-02-13 11:25:01 ! at org.flywaydb.core.Flyway.info(Flyway.java:190)
2024-02-13 11:25:01 ! at marquez.db.DbMigration.hasPendingDbMigrations(DbMigration.java:78)
2024-02-13 11:25:01 ! at marquez.db.DbMigration.migrateDbOrError(DbMigration.java:33)
2024-02-13 11:25:01 ! at marquez.MarquezApp.run(MarquezApp.java:109)
2024-02-13 11:25:01 ! at marquez.MarquezApp.run(MarquezApp.java:51)
2024-02-13 11:25:01 ! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:67)
2024-02-13 11:25:01 ! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
2024-02-13 11:25:01 ! at io.dropwizard.cli.Cli.run(Cli.java:78)
2024-02-13 11:25:01 ! at io.dropwizard.Application.run(Application.java:94)
2024-02-13 11:25:01 ! at marquez.MarquezApp.main(MarquezApp.java:63)
2024-02-13 11:25:01 INFO  [2024-02-13 16:25:01,525] marquez.MarquezApp: Stopping app...
```

**Comment by mobuchowski** [comment]
@merobi-hub no logs from Postgres container?

**Comment by merobi-hub** [comment]
Thanks @mobuchowski . Here are those logs:
```
2024-02-13 16:32:20 The files belonging to this database system will be owned by user "postgres".
2024-02-13 16:32:20 This user must also own the server process.
2024-02-13 16:32:20 
2024-02-13 16:32:20 The database cluster will be initialized with locale "en_US.utf8".
2024-02-13 16:32:20 The default database encoding has accordingly been set to "UTF8".
2024-02-13 16:32:20 The default text search configuration will be set to "english".
2024-02-13 16:32:20 
2024-02-13 16:32:20 Data page checksums are disabled.
2024-02-13 16:32:20 
2024-02-13 16:32:20 fixing permissions on existing directory /var/lib/postgresql/data ... ok
2024-02-13 16:32:20 creating subdirectories ... ok
2024-02-13 16:32:20 selecting dynamic shared memory implementation ... posix
2024-02-13 16:32:20 selecting default max_connections ... 100
2024-02-13 16:32:20 selecting default shared_buffers ... 128MB
2024-02-13 16:32:20 selecting default time zone ... Etc/UTC
2024-02-13 16:32:20 creating configuration files ... ok
2024-02-13 16:32:20 running bootstrap script ... ok
2024-02-13 16:32:20 performing post-bootstrap initialization ... ok
2024-02-13 16:32:20 syncing data to disk ... ok
2024-02-13 16:32:20 
2024-02-13 16:32:20 
2024-02-13 16:32:20 Success. You can now start the database server using:
2024-02-13 16:32:20 
2024-02-13 16:32:20     pg_ctl -D /var/lib/postgresql/data -l logfile start
2024-02-13 16:32:20 
2024-02-13 16:32:20 waiting for server to start....2024-02-13 21:32:20.923 UTC [47] LOG:  starting PostgreSQL 12.6 (Debian 12.6-1.pgdg100+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2024-02-13 16:32:20 2024-02-13 21:32:20.924 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-02-13 16:32:20 2024-02-13 21:32:20.936 UTC [48] LOG:  database system was shut down at 2024-02-13 21:32:20 UTC
2024-02-13 16:32:20 2024-02-13 21:32:20.938 UTC [47] LOG:  database system is ready to accept connections
2024-02-13 16:32:21  done
2024-02-13 16:32:21 server started
2024-02-13 16:32:21 
2024-02-13 16:32:21 /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
2024-02-13 16:32:21 
2024-02-13 16:32:21 waiting for server to shut down...2024-02-13 21:32:21.076 UTC [47] LOG:  received fast shutdown request
2024-02-13 16:32:21 .2024-02-13 21:32:21.076 UTC [47] LOG:  aborting any active transactions
2024-02-13 16:32:21 2024-02-13 21:32:21.077 UTC [47] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
2024-02-13 16:32:21 2024-02-13 21:32:21.078 UTC [49] LOG:  shutting down
2024-02-13 16:32:21 2024-02-13 21:32:21.118 UTC [47] LOG:  database system is shut down
2024-02-13 16:32:21  done
2024-02-13 16:32:21 server stopped
2024-02-13 16:32:21 
2024-02-13 16:32:21 PostgreSQL init process complete; ready for start up.
2024-02-13 16:32:21 
2024-02-13 16:32:20 initdb: warning: enabling "trust" authentication for local connections
2024-02-13 16:32:20 You can change this by editing pg_hba.conf or using the option -A, or
2024-02-13 16:32:20 --auth-local and --auth-host, the next time you run initdb.
2024-02-13 16:32:21 2024-02-13 21:32:21.190 UTC [1] LOG:  starting PostgreSQL 12.6 (Debian 12.6-1.pgdg100+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2024-02-13 16:32:21 2024-02-13 21:32:21.191 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-02-13 16:32:21 2024-02-13 21:32:21.191 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-02-13 16:32:21 2024-02-13 21:32:21.195 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-02-13 16:32:21 2024-02-13 21:32:21.207 UTC [66] LOG:  database system was shut down at 2024-02-13 21:32:21 UTC
2024-02-13 16:32:21 2024-02-13 21:32:21.210 UTC [1] LOG:  database system is ready to accept connections
2024-02-13 16:32:22 2024-02-13 21:32:22.973 UTC [76] ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
2024-02-13 16:32:22 2024-02-13 21:32:22.973 UTC [76] DETAIL:  Key (typname, typnamespace)=(astro_version_check, 2200) already exists.
2024-02-13 16:32:22 2024-02-13 21:32:22.973 UTC [76] STATEMENT:  
2024-02-13 16:32:22 CREATE TABLE astro_version_check (
2024-02-13 16:32:22 singleton BOOLEAN NOT NULL, 
2024-02-13 16:32:22 last_checked TIMESTAMP WITH TIME ZONE, 
2024-02-13 16:32:22 last_checked_by TEXT, 
2024-02-13 16:32:22 CONSTRAINT astro_version_check_pkey PRIMARY KEY (singleton)
2024-02-13 16:32:22 )
2024-02-13 16:32:22 
2024-02-13 16:32:22 
2024-02-13 16:32:22 2024-02-13 21:32:22.973 UTC [78] ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
2024-02-13 16:32:22 2024-02-13 21:32:22.973 UTC [78] DETAIL:  Key (typname, typnamespace)=(astro_version_check, 2200) already exists.
2024-02-13 16:32:22 2024-02-13 21:32:22.973 UTC [78] STATEMENT:  
2024-02-13 16:32:22 CREATE TABLE astro_version_check (
2024-02-13 16:32:22 singleton BOOLEAN NOT NULL, 
2024-02-13 16:32:22 last_checked TIMESTAMP WITH TIME ZONE, 
2024-02-13 16:32:22 last_checked_by TEXT, 
2024-02-13 16:32:22 CONSTRAINT astro_version_check_pkey PRIMARY KEY (singleton)
2024-02-13 16:32:22 )
2024-02-13 16:32:22 
2024-02-13 16:32:22 
2024-02-13 16:32:26 2024-02-13 21:32:26.000 UTC [87] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:26 2024-02-13 21:32:26.000 UTC [87] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:25.999360+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:26 2024-02-13 21:32:26.000 UTC [86] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:26 2024-02-13 21:32:26.000 UTC [86] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:25.999359+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:28 2024-02-13 21:32:28.900 UTC [95] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:28 2024-02-13 21:32:28.900 UTC [95] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:28.899702+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:28 2024-02-13 21:32:28.907 UTC [96] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:28 2024-02-13 21:32:28.907 UTC [96] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:28.906762+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:31 2024-02-13 21:32:31.981 UTC [103] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:31 2024-02-13 21:32:31.981 UTC [103] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:31.980079+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:32 2024-02-13 21:32:32.009 UTC [104] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:32 2024-02-13 21:32:32.009 UTC [104] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:32.008808+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:35 2024-02-13 21:32:35.558 UTC [111] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:35 2024-02-13 21:32:35.558 UTC [111] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:35.557441+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:35 2024-02-13 21:32:35.561 UTC [112] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:35 2024-02-13 21:32:35.561 UTC [112] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:35.559998+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:39 2024-02-13 21:32:39.690 UTC [119] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:39 2024-02-13 21:32:39.690 UTC [119] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:39.689358+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:39 2024-02-13 21:32:39.738 UTC [120] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:39 2024-02-13 21:32:39.738 UTC [120] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:39.736936+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:45 2024-02-13 21:32:45.764 UTC [127] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:45 2024-02-13 21:32:45.764 UTC [127] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:45.763382+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:45 2024-02-13 21:32:45.783 UTC [128] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:45 2024-02-13 21:32:45.783 UTC [128] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:45.782793+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:54 2024-02-13 21:32:54.898 UTC [133] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:54 2024-02-13 21:32:54.898 UTC [133] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:54.897741+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:32:54 2024-02-13 21:32:54.901 UTC [134] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:32:54 2024-02-13 21:32:54.901 UTC [134] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:32:54.899911+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:33:10 2024-02-13 21:33:10.532 UTC [141] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:33:10 2024-02-13 21:33:10.532 UTC [141] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:33:10.530964+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:33:10 2024-02-13 21:33:10.539 UTC [142] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:33:10 2024-02-13 21:33:10.539 UTC [142] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:33:10.538619+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:33:38 2024-02-13 21:33:38.787 UTC [149] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:33:38 2024-02-13 21:33:38.787 UTC [149] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:33:38.786453+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:33:39 2024-02-13 21:33:39.840 UTC [151] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:33:39 2024-02-13 21:33:39.840 UTC [151] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:33:39.839192+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:34:32 2024-02-13 21:34:32.492 UTC [158] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:34:32 2024-02-13 21:34:32.492 UTC [158] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:34:32.491276+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:34:33 2024-02-13 21:34:33.524 UTC [160] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:34:33 2024-02-13 21:34:33.524 UTC [160] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:34:33.523405+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:35:35 2024-02-13 21:35:35.036 UTC [167] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:35:35 2024-02-13 21:35:35.036 UTC [167] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:35:35.035745+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:35:36 2024-02-13 21:35:36.043 UTC [169] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:35:36 2024-02-13 21:35:36.043 UTC [169] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:35:36.042530+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:42:16 2024-02-13 21:42:16.102 UTC [176] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:42:16 2024-02-13 21:42:16.102 UTC [176] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:42:16.100915+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:42:17 2024-02-13 21:42:17.023 UTC [178] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:42:17 2024-02-13 21:42:17.023 UTC [178] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:42:17.022526+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:43:18 2024-02-13 21:43:18.646 UTC [185] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:43:18 2024-02-13 21:43:18.646 UTC [185] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:43:18.645354+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:43:19 2024-02-13 21:43:19.463 UTC [187] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:43:19 2024-02-13 21:43:19.463 UTC [187] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:43:19.462511+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:44:21 2024-02-13 21:44:21.222 UTC [195] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:44:21 2024-02-13 21:44:21.222 UTC [195] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:44:21.221115+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:44:21 2024-02-13 21:44:21.884 UTC [196] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:44:21 2024-02-13 21:44:21.884 UTC [196] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:44:21.883080+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:45:23 2024-02-13 21:45:23.841 UTC [203] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:45:23 2024-02-13 21:45:23.841 UTC [203] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:45:23.840169+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:45:24 2024-02-13 21:45:24.588 UTC [205] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:45:24 2024-02-13 21:45:24.588 UTC [205] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:45:24.584661+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:46:26 2024-02-13 21:46:26.381 UTC [212] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:46:26 2024-02-13 21:46:26.381 UTC [212] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:46:26.380092+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:46:27 2024-02-13 21:46:27.158 UTC [214] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:46:27 2024-02-13 21:46:27.158 UTC [214] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:46:27.157595+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:47:28 2024-02-13 21:47:28.919 UTC [222] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:47:28 2024-02-13 21:47:28.919 UTC [222] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:47:28.918077+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "09715d2eb60f", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2024-02-13 16:47:29 2024-02-13 21:47:29.588 UTC [223] ERROR:  relation "log" does not exist at character 13
2024-02-13 16:47:29 2024-02-13 21:47:29.588 UTC [223] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2024-02-13T21:47:29.587654+00:00'::timestamptz, 'cli_migratedb', 'astro', '{"host_name": "1fd0181885e6", "full_command": "[''/usr/local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
```
